version: '3.5'

x-services:
  base: &base-api
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URI: postgresql+psycopg2://$DB_USER:$DB_PASSWORD@$DB_HOST:$CONN_DB_PORT/$DB_NAME
      API_PORT: $API_PORT
    volumes:
      - .:/src

services:
  api:
    <<: *base-api
    ports: ['$API_PORT:$API_PORT']
    command: bash -c "cd /src && ./scripts/wait-for-it.sh $DB_HOST:$CONN_DB_PORT && ./scripts/runserver.sh"

  postgres:
    image: postgres:10.5
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports: ['${HOST_BIND_DB_PORT}:5432']
    restart: on-failure


  tests:
    <<: *base-api
    container_name: tests
    command: bash -c "cd /src && pytest --junitxml=/src/api/tests/results.xml"
